### ISSUE TITLE
Orthophotos - file name after download

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#100]
After clipping and shipping from http://haitidata.dev.ithacaweb.org/clip/ortho_images, the file has the following format name:

Orthoimage de la **zone urbaine de Port-au-Prince.tif**.AAAA-MM-DD_HH-MM-SS.tif

I suggest to name it: Orthoimage_HaitiData_AAAA-MM-DD_HH-MM-SS.tif

Anyway If we can have a detail on the location would be perfect.

**Comment by ppasq** [comment]
The name is given by the corresponding layer. Both were changed accordingly.
