### ISSUE TITLE
Rancher Training

### ISSUE THREAD

**Issue by cchristelis** [HaitiData/haitidata#11]
# Problem

Since the Haiti Team will need to be able to administer the site, we need to have training materials prepared around the rancher configuration.

# Proposed Solution

Set up training documents on how to use the rancher instance.

**Comment by cchristelis** [comment]
@euclidian

**Comment by euclidian** [comment]
Please take a look at this https://docs.google.com/document/d/1jIlXp-7GC9L6CpUaNoc5cnHRwibN61Nw0JxjZzNI0Dw/edit#. I'll try to tidy it up more

**Comment by cchristelis** [comment]
@dimasciput, have you been able to incorporate these into actual work-sheets?

**Comment by dimasciput** [comment]
Not yet, will going to work on this today-tomorrow. Do we need video tutorial too?
