### ISSUE TITLE
Lidar/DEM page

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#113]
Can we change the title into DEM or DTM instead of DSM?

Can we add the following text above the clip-n-ship window?:

> Un Modèle Numérique de Terrain (MNT) est une représentation 3D de la surface d'un terrain ou d'une planète, créée à partir des données d'altitude du terrain. Le MNT ne prend pas en compte les objets présents à la surface du terrain tels les plantes et les bâtiments. Pour mieux comprendre comment sélectionner la zone d’intérêt, voir le tutoriel: https://haitidata…tutoriels.org
> La taille maximale accepté est de 40 megabytes

**Comment by AndreaAjmar** [comment]
I'm not completely sure of the nature of the LiDAR product: it seems something mid road between a DSM and a DTM.

e.g.
bridges are clearly identifiable (that means that this product, as it is, cannot be used for hydrological modeling):
![screen shot 2017-10-29 at 14 44 42](https://user-images.githubusercontent.com/13776909/32144396-5f39ca52-bcb8-11e7-81ba-3d503d21ea96.png)

the same for the (relatively) high-rise built-up elements (Mupanah and a fountain?) in Place Jean-Jacques Dessalines:
![screen shot 2017-10-29 at 14 53 28](https://user-images.githubusercontent.com/13776909/32144465-a073d804-bcb9-11e7-86dd-1bbe34b194d6.png)

But in general low-lying buildings seems to have been filtered.

gmtoglia can you verify which post-processing steps has been applied? According to this we can apply the most appropriate acronym and description to the dataset.

**Comment by AndreaAjmar** [comment]
Yes, but the text you propose for the description is not 100% right, as actually the dataset considers some of the object on top of the ground (e.g. bridges, monuments/high-rise buildings, etc.)

Therefore, I suggest to:
- use the label DEM (English) or MNT (French)
- revise the description as following:
Un Modèle Numérique de Terrain (MNT) est une représentation 3D de la surface d'un terrain ou d'une planète, créée à partir des données d'altitude du terrain. Pour mieux comprendre comment sélectionner la zone d’intérêt, voir le tutoriel: http://haitidata.org/tutorials/
La taille maximale accepté est de 40 megabytes

**Comment by gmtoglia** [comment]
Perfect, let's use this new text:


Un Modèle Numérique de Terrain (MNT) est une représentation 3D de la
surface d'un terrain ou d'une planète, créée à partir des données
d'altitude du terrain. Pour mieux comprendre comment sélectionner la zone
d’intérêt, voir le tutoriel: "http://haitidata.org/tutorials#idTutorial"
*Ces prises de vu sur Haiti ont été faites entre le 2014 et le 2016.*
La taille maximale accepté est de 40 megabytes

Thank you Andrea!

2017-10-29 10:33 GMT-04:00 Andrea Ajmar <notifications@github.com>:

**Comment by gmtoglia** [comment]
New version of the text:

Un Modèle Numérique de Terrain (MNT) est une représentation 3D de la
surface d'un terrain ou d'une planète, créée à partir des données
d'altitude du terrain. Pour mieux comprendre comment sélectionner la zone
d’intérêt, voir le tutoriel: "http://haitidata.org/tutorials#idTutorial"
Ces prises de vu sur Haiti ont été faites entre le 2014 et le 2016.

Pour sélectionner la zone d’intérêt:
- Cliquer sur l'icône ![image](https://user-images.githubusercontent.com/16922193/32183747-8037c78c-bd70-11e7-93cb-a9f91ce2094b.png) pour utiliser un polygone irrégulier
- Cliquer sur l'icône ![image](https://user-images.githubusercontent.com/16922193/32183863-d7069f5c-bd70-11e7-9f05-adc6a4fa93a7.png) pour utiliser un rectangle comme forme de base

La taille maximale accepté est de 40 megabytes
