### ISSUE TITLE
Official user creation

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#118]
Can we have the procedure to create an official user?

![image](https://user-images.githubusercontent.com/16922193/32180172-a199ca32-bd67-11e7-88d4-a84433c7924d.png)

**Comment by ppasq** [comment]
1. Add the "official user" username to the resourcebase_snippet template https://github.com/HaitiData/haitidata/blob/master/haitidata/templates/base/_resourcebase_snippet.html#L12 
2. Upload a PNG only avatar with no transparency. For better results use a square image.
