### ISSUE TITLE
Clip and ship layer error

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#139]
When I try to download an area, I get this error (on the production platform "haitidata.org"):

![image](https://user-images.githubusercontent.com/16922193/32744193-bddd34ca-c87c-11e7-86d7-af198b3d7f92.png)

**Comment by cchristelis** [comment]
@dimasciput, please explain how this bug was introduced? I am sure this was not present on Friday...

**Comment by gmtoglia** [comment]
On the dev platform: http://haitidata.dev.ithacaweb.org/clip/ortho_images everything works fine.

**Comment by dimasciput** [comment]
I fixed it, we tried to adding a new pyramid ortho images yesterday (http://haitidata.org/layers/geonode:ortho_images) and it conflicts with this layer. But it should be fine now.
