### ISSUE TITLE
Poor performances - Cannot open maps on production website

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#140]
In the following video you can see the performance difference between the development and the production website

https://drive.google.com/open?id=1HafNfimXQfyiXT7S2ONVE_z4wxzhcyux

The final result on the production website was this:

![image](https://user-images.githubusercontent.com/16922193/32862551-6e93fa4c-ca26-11e7-8fa5-b8bc7594c64a.png)

**Comment by dimasciput** [comment]
@gmtoglia We have updated the geoserver configuration, and for now we will keep monitoring the performance. The issue we found was because memory configuration in geoserver container.

**Comment by gmtoglia** [comment]
Today at 7PM Haiti time, the performance problem showed up again:

![image](https://user-images.githubusercontent.com/16922193/33245795-49c7335c-d2da-11e7-9780-1814f04212ce.png)

**Comment by cchristelis** [comment]
This seems to be due to a memory leak.  Also please disallow downloading large layer's data.

**Comment by dimasciput** [comment]
One of the issues with this is because users try to download lidar or ortho layer, and they are too big. Now we have removed the download permission for public users. 

We will still monitor the performance of the geoserver, and so far there's no problem.
