### ISSUE TITLE
Impossible download layer as “tile”

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#141]
When an use chose to download a layers as “image->tile” this is the result:

![Image](https://i.imgur.com/pWb9xwI.jpg)

**Comment by Gustry** [comment]
This link is a kind of stream, that you need to use in a GIS software/library such as QGIS. It's like a WMS link, we can't use it in a webbrowser.

**Comment by cchristelis** [comment]
Thanks for the clarification @Gustry, could you perhaps advise how this would be done in QGIS and then close this issue, please.

**Comment by Gustry** [comment]
![tiles](https://user-images.githubusercontent.com/1609292/32944658-95b315a2-cb90-11e7-96f5-933073c91019.gif)

* Copy the tiles URL
* In QGIS or in another software/library which is able to manage a TMS (Tile Map Service)
* Create a new connection with the tile URL
  * In the QGIS Browser, right click on `Tile Server XYZ`, add new connection with the URL

**Comment by gmtoglia** [comment]
Thank you very much Etienne.
Now I understand . Do you think we can add this (btw very useful and clear) clip in the tutorials page?
