### ISSUE TITLE
Develop Branch and PR Review

### ISSUE THREAD

**Issue by euclidian** [HaitiData/haitidata#15]
We've discussed about creating a develop branch where we should merge all open PRs. Is this possible? And I think PR #7 should be reviewed soon, because it keeps getting bigger.

**Comment by ppasq** [comment]
A development branch has been created. PR #7 will be reviewed soon.

**Comment by cchristelis** [comment]
@euclidian, could you please open a new PR and point it to the develop branch.

**Comment by euclidian** [comment]
done
