### ISSUE TITLE
Error 502 when logging in

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#157]
Happened on the 8th of December, it was impossible to login.
![bug](https://user-images.githubusercontent.com/16922193/34123128-86a55276-e3fc-11e7-8552-b2a4d1fc2677.png)

**Comment by AndreaAjmar** [comment]
This happened on 15th of December too. We noticed that at the same time geoServer too was inaccessible (504 Gateway Time-out error)

**Comment by dimasciput** [comment]
This is fine now, maybe the server was slow at that time.

**Comment by cchristelis** [comment]
@dimasciput, has this issue been resolved or is it an intermittent issue? Do we have any logs that could help us understand what happened?

**Comment by sbsimo** [comment]
I had a similar issue on the dev server, when I upgraded the django container. 
In that case I had to restart the nginx container, to make the system work correctly again.

As the issue did not repeat recently, I would close it.
