### ISSUE TITLE
String length issue when showing categories

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#16]
The user cannot see the whole string if it's too long:

![image](https://user-images.githubusercontent.com/16922193/30342916-8f350b9a-97c9-11e7-9861-b302763e1410.png)

The number of layers related is also out of the line.

**Comment by ppasq** [comment]
![screen shot 2017-09-27 at 11 26 41](https://user-images.githubusercontent.com/3024454/30906012-c5cf4c70-a376-11e7-9081-f39e062c2ca0.png)
