### ISSUE TITLE
Issue to download data

### ISSUE THREAD

**Issue by edejude** [HaitiData/haitidata#164]
Dear all,

The feature 'Download shape files' is not working properly. Here is the message response
![image](https://user-images.githubusercontent.com/3659579/38882428-104ff6f4-4238-11e8-8842-8908ea12a303.png)

**Comment by ppasq** [comment]
It seems related to that particular layer. Are you getting this error with other layers?

**Comment by edejude** [comment]
Apparently, the download does not work on any layer, including documents and orthophotos.

**Comment by ppasq** [comment]
It seems it was due to a lack resources. Now it works fine for me. Could you please double-check?

**Comment by edejude** [comment]
It works for me too. Thank you so much.
