### ISSUE TITLE
Shapefile corrupted after download

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#17]
When downloading the following Zipped shapefile, the file is corrupted:

http://haitidata.dev.ithacaweb.org/layers/geonode:routet#map=611.49622628141/-8130377.31/2160698.12/0

**Comment by AndreaAjmar** [comment]
The development instance has been reset and layers reloaded, therefore I'm not currently able to retrieve the layer generating the corrupted zip file
