### ISSUE TITLE
Set locale to en_US.UTF-8

### ISSUE THREAD

**Issue by ppasq** [HaitiData/haitidata#22]
Current locale is en_ZA.UTF-8

**Comment by meomancer** [comment]
hi @ppasq 
i see it breaks account insertion as you mention as in email
```
I've encountered several issues. I've started from scratch, make a fresh-deploy but when I create a new superuser I get the first error (that didn't occur before).  After confirming the user password I get 

django.db.utils.DataError: value too long for type character varying(10)
```

https://github.com/GeoNode/geonode-user-accounts/blob/master/account/models.py#L36
it has max length=10 but the locale we use is more than 10

My solution is as them to update their model, or maybe remove UTF8 or maybe we could fork their repo and update by ourself.

**Comment by ppasq** [comment]
hi @meomancer 
this could be worth asking the GeoNode Dev list.

**Comment by cchristelis** [comment]
Let's try en.UTF-8

**Comment by meomancer** [comment]
hi @cchristelis 
after i try it, it seems no locale en.UTF-8 found
