### ISSUE TITLE
Store shapefile to PostGIS

### ISSUE THREAD

**Issue by dimasciput** [HaitiData/haitidata#29]
## Problem

When you upload a shapefile the layer is stored on filesystem and not in PostGIS. This behaviour affects the osgeo-importer.

## Solution

Store shapefile to PostGIS.

**Comment by ppasq** [comment]
GeoServer is not able to connect to the database. When uploading a layer I'm getting the following error:

`Error deleting PostGIS table gis_osm_landuse_a_free_1:could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?`

**Comment by ppasq** [comment]
Database geonode_data is not created with fresh-deploy. Store configuration is not correct (host, user and password).
