### ISSUE TITLE
Replace filler text

### ISSUE THREAD

**Issue by ppasq** [HaitiData/haitidata#35]
Review text and fill-ins (Lorem ipsum)

**Comment by AndreaAjmar** [comment]
Actions:
- provide test for the imagery section -> **gmtoglia/CNIGS**
![image](https://user-images.githubusercontent.com/13776909/31347787-c56e674c-ad1d-11e7-8075-d7589a0e9eda.png)
- update text and add button pointing to the specific pages -> **ppasq**
