### ISSUE TITLE
Tutorials missing

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#45]
The tutorials for the use of the platform are missing (chapter 1.7 of the technical proposal)

**Comment by cchristelis** [comment]
Hi @Gustry and @dimasciput, could you guys combine efforts to do a 3min overview of the ship'n'clip tool.

**Comment by ppasq** [comment]
The proposal is to have 10 x 3 mins video tutorials highlighting the main functionalities. We should agree a list of the 10 topics.

**Comment by cchristelis** [comment]
Let's maintain a list here and also who is responsible
- Rancher [Kartoza]
- Ship and Clip [Kartoza]
-

**Comment by cchristelis** [comment]
@dimasciput and @Gustry, how is the 'ship and clip' tutorial coming along?

**Comment by Gustry** [comment]
The video about ship and clip: https://www.youtube.com/watch?v=6pcCoOYe0uY

Is-it ok like this?

**Comment by gmtoglia** [comment]
Yes Etienne, this video explains very well the feature. I have only two suggestions: 1[not necessary but could help])to use a raster where the picture is more "user-friendly/satellite image" (like this:http://haitidata.dev.ithacaweb.org/layers/geonode:Haiti25cm-PaP-extract#map=152.8740565703525/-8039877.97/2096636.59/0). 2[I think that this is important]) show a scenario where the clip and ship works (I see that the downloaded image was not the one clipped, am I right?)

**Comment by Gustry** [comment]
1. Yes, I understand. I took the SRTM available on this geonode: http://88.99.166.60/layers/?limit=100&offset=0
2. Hum ..., I restarted the video many times, to have the perfect voice and scenario ;-) Maybe I opened the wrong zip file! Sorry for that, let me check.

**Comment by gmtoglia** [comment]
Can we have two columns (centered) for the videos list? Thank you!

**Comment by AndreaAjmar** [comment]
First 3 ITHACA tutorials available:
Graphiques interactifs: https://youtu.be/BkQANF6DNhg
ODK: https://youtu.be/Wx3-QeqF63A
Sharing layers and metadata: https://youtu.be/xku8-K995_M

**Comment by AndreaAjmar** [comment]
Update on the tutorials:
->Rancher [Kartoza]: TBD
->Ship and Clip [Kartoza]: draft available at https://www.youtube.com/watch?v=6pcCoOYe0uY and on Tutoriels page
->Sharing layers and metadata [ITHACA]  -> draft available https://youtu.be/xku8-K995_M and on Tutoriels page
->Uploading files from Android ODK [ITHACA]  -> draft available https://youtu.be/Wx3-QeqF63A and on Tutoriels page
->Styling layers  [ITHACA] -> draft available https://youtu.be/H14DMxuv-VI
->Creating maps [ITHACA] -> draft available https://youtu.be/ajOUe7HUgUY
->Charts [ITHACA]  -> draft available https://youtu.be/BkQANF6DNhg and on Tutoriels page
->Platform overview [ITHACA] -> draft available https://youtu.be/VvAEUH_gaes
->Managing users [ITHACA] -> draft available https://youtu.be/oVcDq1jHeNA
->Search filters [ITHACA] -> draft available https://youtu.be/_0ya71tJnWY

**Comment by ppasq** [comment]
All available tutorials (only one missing) have been added to the page.

**Comment by gmtoglia** [comment]
The volume of this tutorial is too low: https://www.youtube.com/watch?v=VvAEUH_gaes - we wanted to use it to present the platform during the conference press but we can't.

**Comment by AndreaAjmar** [comment]
We already have a audio track and now coupling it with the video in order to provide a new version of the videos

**Comment by AndreaAjmar** [comment]
It was discussed to create a specific YouTube channel to store the tutorials: I suggest that CNIGS creates this channel using an account managed by this institution. If available in time and all tutorials loaded there, we can take care to link the HaitiData tutorial page to this channel for the press conference

**Comment by gmtoglia** [comment]
I agree Andrea. The CNIGS will create an account on YouTube to host the
tutorials. In theory there is one already:
https://www.youtube.com/channel/UCJgvfOUwqAPTFmzPP__HJKw/featured but we
still don't have the greenlight from the government to use it (because it's
based on a gmail account: *cnigshaiti@gmail.com <cnigshaiti@gmail.com>*,
that we used for another project, and not on a *xyz@cnigs.ht <xyz@cnigs.ht>
*account).
In the meantime, can we just replace the existing videos with the new ones?
When you consider the tutorials done, you can just send us the videos (via
WeTranfer) and we'll upload them on the channel. Once done, we can
follow-up with you to change the embedded links. Is it ok for you?

2017-11-08 10:09 GMT-05:00 Andrea Ajmar <notifications@github.com>:
