### ISSUE TITLE
Download clip - error management when not selecting the area

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#46]
If the user wants to download a clip without selecting the area, the message "No polygon in map, this will clip from map extent instead" appears and the download is impossible (the user has to refresh the page in order to try again).

**Comment by dimasciput** [comment]
### Error Report

Using this command to get clipped tiff from bbox string
```
gdal_translate -projwin ulx uly lrx lry inraster.tif outraster.tif
```

Got an error : 
```
ERROR 1: Error: Computed -srcwin 732 1.15436e+06 1.15432e+06 -1.15417e+06 has negative width and/or height.
```

Gdal version : 2.1.3

**Comment by dimasciput** [comment]
Fixed in https://github.com/HaitiData/haitidata/pull/53
