### ISSUE TITLE
Enhancement: automatic link into the viewer

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#5]
When the user creates a layer, it's not possible to click on a link in the viewer. Is it possible to recognize a string starting with "http..." and make it clickable? It would be perfect if: 
- the link will be open in a new tab 
- the url string will be reduced to a "tiny url"

Example: http://haitidata.dev.ithacaweb.org/layers/geonode:test_form_undp_results3_cc4b4f8c#map=0.009330691929342804/-8049083.75/2100607.33/0

http://haitidata.dev.ithacaweb.org/layers/geonode:test_form_haitidata_v002_d1cb9bcd#map=0.009330691929342804/-8049083.76/2100607.33/0

**Comment by AndreaAjmar** [comment]
Hyperlinks in the viewer are strongly discouraged for security reasons.
Furthermore, as we decided to work with mosaics, the single imagery/DEM tiles will not be added as individual GeoNode/HaitiData layers: therefore, this enhancement is no more needed
