### ISSUE TITLE
Risk and Hazard Panel

### ISSUE THREAD

**Issue by cchristelis** [HaitiData/haitidata#63]
# Question

I was looking through the site and came across the Risk and Hazard section and was not entirely sure how to use this section:
<img width="1303" alt="screen shot 2017-10-03 at 8 57 58 pm" src="https://user-images.githubusercontent.com/2319504/31143528-ce3ab03c-a87d-11e7-8f2b-a68a317cd242.png">

What is the purpose of this?

**Comment by ppasq** [comment]
Data about specific risk and hazards analysis are available in the platform. This section is a quick link to that data (based on keywords).
