### ISSUE TITLE
Uploads and upload csv

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#65]
Is there a more user friendly way to give access to the "Upload CSV" feature?

![image](https://user-images.githubusercontent.com/16922193/31187464-0812117e-a900-11e7-9aa9-8cb13350ccac.png)

**Comment by ppasq** [comment]
What about a more general "Upload ODK exports"?

**Comment by gmtoglia** [comment]
Perfect!

**Comment by ppasq** [comment]
Any kind of CSV but the importer recognises only the following columns as longitude and latitude: 'Lon*', 'Lat*'; 'x', 'y'; '*Longitude', '*Latitude' (the latter are from ODK). In addition the following columns as geometry: 'geom', 'GEOM', 'WKT', 'the_geom', 'THE_GEOM', 'WKB', 'wkb_geometry'.

**Comment by gmtoglia** [comment]
Ok, we can label it "Upload ODK exports". Thank you!
