### ISSUE TITLE
Delete CSV

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#66]
The button "delete" of a CSV file doesn't work on Google Chrome
![image](https://user-images.githubusercontent.com/16922193/31194855-65f28d9e-a916-11e7-9f3a-269a619dc26b.png)

**Comment by AndreaAjmar** [comment]
I tried to delete the upload and it worked, both without creating a layer and after having created a layer.

Tested using Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Windows
