### ISSUE TITLE
Unable to clip a mosaic

### ISSUE THREAD

**Issue by ppasq** [HaitiData/haitidata#67]
Tried the clip-and-ship tool against a mosaic. The orthophoto mosaic is availabale at:
http://haitidata.dev.ithacaweb.org/layers/geonode:Haiti25cm-PaP-extract

The error I get is:
```
 Internal Server Error: /clip/geonode:Haiti25cm-PaP-extract/clip-layer
 Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/home/ubuntu/haitidata/clip-and-ship/views.py", line 47, in clip_layer
     for layerfile in layer.upload_session.layerfile_set.all():
 AttributeError: 'NoneType' object has no attribute 'layerfile_set'
```

**Comment by dimasciput** [comment]
I can't seems to download the layer, can you provide us the layer? Thanks.

**Comment by ppasq** [comment]
You can find the layer on the production server in cnigs-data/ortho_images. You don't need to use all the granules and this particular set of images. The error can be reproduced with mosaics created by GeoServer. In case, you can use WCS for mosaics instead of GDAL for clipping.

**Comment by meomancer** [comment]
hi @ppasq 
could you describe what did you do? what i mean, is these files uploaded through geonode? or it is created on geoserver?
how to do it? and how to reproduce it?
it seems that from code, the files is not found on geonode side

**Comment by ppasq** [comment]
The mosaics were added following this tutorial http://docs.geonode.org/en/master/tutorials/advanced/adv_data_mgmt/adding_data/mosaic.html
Then inserted in GeoNode thru manage.py updatelayers
