### ISSUE TITLE
Categories and kind of risk/hazard

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#72]
I see that in the home page there is a filter by kind of risk/hazard
![image](https://user-images.githubusercontent.com/16922193/31294944-c4297194-aaaa-11e7-813a-6a846de6e2a9.png)

How can I set-up this information for a layer? I was not able to find it in the metadata page. 

![image](https://user-images.githubusercontent.com/16922193/31295005-f171b8f0-aaaa-11e7-9cb1-79599934699a.png)

**Comment by ppasq** [comment]
You must add the corresponding keywords (Keywords input text in metadata page):

- River Flood -> flood
- Cyclone -> cyclone
- Coastal Flood -> coastal-flood
- Earthquake -> earthquake
- Water Scarcity -> water-scarcity
- Landslide -> landslide

**Comment by gmtoglia** [comment]
Perfect. I believe that for the french version we just have to translate the keywords.

**Comment by ppasq** [comment]
OK, no problem.
