### ISSUE TITLE
Clip-n-ship: delete and edit

### ISSUE THREAD

**Issue by gmtoglia** [HaitiData/haitidata#86]
The **icons** for "delete" and "edit" in the clip-n-ship window are "upside down" (the bin is used to "edit" and the pen is used to "delete")

![image](https://user-images.githubusercontent.com/16922193/31563583-b40f73d4-b02d-11e7-9950-6e192a7252fb.png)

**Comment by meomancer** [comment]
hi @gmtoglia 
it seems the svg is not correct
here is from haitidata
https://github.com/HaitiData/haitidata/blob/master/haitidata/static/geonode/css/images/spritesheet.svg

maybe we could use from development branch?
https://github.com/HaitiData/haitidata/blob/development/django_project/core/geonode_static/geonode/css/images/spritesheet.svg

here is from development branch
![selection_023](https://user-images.githubusercontent.com/4530905/31771841-c078d762-b507-11e7-95f8-e7f411beea75.png)

**Comment by gmtoglia** [comment]
Yes,
The développement branch solution si fine. Thank you.

**Comment by ppasq** [comment]
I've fixed the svg. I will update in test as well.
