### ISSUE TITLE
Replace GeoNode with Haitidata in tab description

### ISSUE THREAD

**Issue by AndreaAjmar** [HaitiData/haitidata#98]
![screen shot 2017-10-25 at 00 34 27](https://user-images.githubusercontent.com/13776909/31971519-7f331a1a-b91c-11e7-9125-671c9bcd0d7f.png)
![screen shot 2017-10-25 at 00 36 29](https://user-images.githubusercontent.com/13776909/31971569-a669abee-b91c-11e7-8564-9f4cba801c84.png)
![screen shot 2017-10-25 at 00 37 36](https://user-images.githubusercontent.com/13776909/31971589-bc357d54-b91c-11e7-9026-af0f734de8c6.png)
etc.

**Comment by ppasq** [comment]
Display name was set in Django Admin.
