### ISSUE TITLE
Error when trying to save a chart with Quantity set to Null

### ISSUE THREAD

**Issue by AndreaAjmar** [HaitiData/haitidata#99]
While creating a chart with Quantity set as null:
![screen shot 2017-10-25 at 16 21 04](https://user-images.githubusercontent.com/13776909/32003822-8f6da97a-b9a0-11e7-839d-eb16d95d9ee3.png)

the preview generate a (meaningless?) chart:
![screen shot 2017-10-25 at 16 22 21](https://user-images.githubusercontent.com/13776909/32003870-bc650446-b9a0-11e7-9a56-e23de05c51ca.png)

but the Save button generate an error:
![screen shot 2017-10-25 at 16 23 34](https://user-images.githubusercontent.com/13776909/32003935-e6510278-b9a0-11e7-9e5a-345279c822d9.png)

(tested on "Infrastructures dans les Zones Scolaires" layer)

**Comment by AndreaAjmar** [comment]
With Aggregation set to Category count:
![screen shot 2017-10-25 at 16 31 01](https://user-images.githubusercontent.com/13776909/32004423-04adc0ac-b9a2-11e7-902b-ba5af0eccf81.png)

the produced chart as a meaning:
![screen shot 2017-10-25 at 16 32 42](https://user-images.githubusercontent.com/13776909/32004494-299fe534-b9a2-11e7-956b-0347a73671a0.png)

But still have the same error when trying to save

**Comment by sbsimo** [comment]
Solution proposed in https://github.com/ppasq/haitidata/pull/19
Re-assigned to @ppasq for merging and publishing on the server.

**Comment by sbsimo** [comment]
Merged by ppasq.
Re-assigned to @AndreaAjmar for checking and closing or commenting further.
